ci: finalize ci/cd

diff --git a/.github/workflows/CI_CD.yml b/.github/workflows/CI_CD.yml
--- a/.github/workflows/CI_CD.yml
+++ b/.github/workflows/CI_CD.yml
@@ -27,7 +27,7 @@ on:
         - major
 
   release:
-    types: [published]
+    types: [created]
 
 #authorization to private github
 permissions:
@@ -37,67 +37,67 @@ permissions:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  pre-commit:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-    - name: Configure Node
-      uses: actions/setup-node@v4
-      with:
-        node-version: 20
-    - uses: actions/setup-python@v3
-    - uses: pre-commit/action@v3.0.0
+  # pre-commit:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v4
+  #   - name: Configure Node
+  #     uses: actions/setup-node@v4
+  #     with:
+  #       node-version: 20
+  #   - uses: actions/setup-python@v3
+  #   - uses: pre-commit/action@v3.0.0
 
-  verifications:
-    runs-on: ubuntu-latest
-    needs: [ pre-commit ]
-    name: Vérifications
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          show-progress: false
-      - name: Configure Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-      # Runs a single command using the runners shell
-      - name: Install dependencies
-        run: npm ci
-      - name: Run TU
-        run: npm run test:coverage
-      - name: Run lint
-        run: npm run lint
-      - name: Publish TU Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Vitest Tests                  # Name of the check run which will be created
-          path: testsReports/test-junit.xml      # Path to test results (inside artifact .zip)
-          reporter: jest-junit              # Format of test results
+  # verifications:
+  #   runs-on: ubuntu-latest
+  #   needs: [ pre-commit ]
+  #   name: Vérifications
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         show-progress: false
+  #     - name: Configure Node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20
+  #     # Runs a single command using the runners shell
+  #     - name: Install dependencies
+  #       run: npm ci
+  #     - name: Run TU
+  #       run: npm run test:coverage
+  #     - name: Run lint
+  #       run: npm run lint
+  #     - name: Publish TU Report
+  #       uses: dorny/test-reporter@v1
+  #       if: success() || failure()
+  #       with:
+  #         name: Vitest Tests                  # Name of the check run which will be created
+  #         path: testsReports/test-junit.xml      # Path to test results (inside artifact .zip)
+  #         reporter: jest-junit              # Format of test results
 
-  build:
-    runs-on: ubuntu-latest
-    needs: [ verifications ]
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Configure Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-      - name: Install nuxt
-        run: npm install nuxt
-      - name: Run a one-line script
-        run: npm run build
+  # build:
+  #   runs-on: ubuntu-latest
+  #   needs: [ verifications ]
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Configure Node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20
+  #     - name: Install nuxt
+  #       run: npm install nuxt
+  #     - name: Run a one-line script
+  #       run: npm run build
 
   create_and_publish_new_version:
       if: github.event_name == 'workflow_dispatch'
       runs-on: ubuntu-latest
-      needs: [ build ]
+      # needs: [ build ]
       permissions:
         contents: write
       steps:
