ci: reorganise yaml file

diff --git a/.github/workflows/CI_CD.yml b/.github/workflows/CI_CD.yml
--- a/.github/workflows/CI_CD.yml
+++ b/.github/workflows/CI_CD.yml
@@ -46,62 +46,62 @@ jobs:
     - uses: actions/setup-python@v3
     - uses: pre-commit/action@v3.0.0
 
-  verif:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-    needs: [ pre-commit ]
-    name: Vérifications
+  # verif:
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
+  #   needs: [ pre-commit ]
+  #   name: Vérifications
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          show-progress: false
-      - name: Configure Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-      # Runs a single command using the runners shell
-      - name: Install dependencies
-        run: npm ci
-      - name: Run TU
-        run: npm run test:coverage
-      - name: Run lint
-        run: npm run lint
-      - name: Publish TU Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Vitest Tests                  # Name of the check run which will be created
-          path: testsReports/test-junit.xml      # Path to test results (inside artifact .zip)
-          reporter: jest-junit              # Format of test results
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         show-progress: false
+  #     - name: Configure Node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20
+  #     # Runs a single command using the runners shell
+  #     - name: Install dependencies
+  #       run: npm ci
+  #     - name: Run TU
+  #       run: npm run test:coverage
+  #     - name: Run lint
+  #       run: npm run lint
+  #     - name: Publish TU Report
+  #       uses: dorny/test-reporter@v1
+  #       if: success() || failure()
+  #       with:
+  #         name: Vitest Tests                  # Name of the check run which will be created
+  #         path: testsReports/test-junit.xml      # Path to test results (inside artifact .zip)
+  #         reporter: jest-junit              # Format of test results
 
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-    needs: [ verif ]
+  # # This workflow contains a single job called "build"
+  # build:
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
+  #   needs: [ verif ]
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Configure Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-      - name: Install nuxt
-        run: npm install nuxt
-      - name: Run a one-line script
-        run: npm run build
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Configure Node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20
+  #     - name: Install nuxt
+  #       run: npm install nuxt
+  #     - name: Run a one-line script
+  #       run: npm run build
 
   increment-version:
       if: github.event_name == 'workflow_dispatch'
       runs-on: ubuntu-latest
-      needs: [ build ]
+      needs: [ pre-commit ]
       permissions:
         contents: write
       steps:
@@ -125,32 +125,29 @@ jobs:
             git push --tags origin develop
           env:
             VERSION: ${{ inputs.version }}
-
-  new-release:
-    if: github.event_name == 'workflow_dispatch'
-    runs-on: ubuntu-latest
-    needs: [ increment-version ]
-    permissions:
-      contents: write
-    steps:
-      - name: Récupérer le dernier tag
-        id: get_last_tag
-        run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
-      - name: Créer une release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ steps.get_last_tag.outputs.tag }}
-          release_name: Release ${{ steps.get_last_tag.outputs.tag }}
-          body: |
-            Nouvelle release effectuée.
-          draft: false
-          prerelease: false
+        - name: Récupérer le dernier tag
+          id: get_last_tag
+          run: echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
+        - name: Créer une release
+          id: create_release
+          uses: actions/create-release@v1
+          env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          with:
+            tag_name: ${{ steps.get_last_tag.outputs.tag }}
+            release_name: Release ${{ steps.get_last_tag.outputs.tag }}
+            body: |
+              Nouvelle release publiée
+            draft: false
+            prerelease: false
+        # - name: Package Node
+        #   uses: actions/setup-node@v3
+        #   with:
+        #     node-version: '20.x'
+        #     registry-url: 'https://registry.npmjs.org'
+        # - run: npm publish --access public
+        #   env:
+        #     NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
 
   publish-release:
     if: github.event_name == 'workflow_dispatch'
@@ -166,34 +163,34 @@ jobs:
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
 
-  deploy_mkdocs:
-    needs: [ pre-commit ]
-    permissions:
-      id-token: write
-      pages: write
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out
-        uses: actions/checkout@v4
-        with:
-          token: "${{ secrets.PAT }}"
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: "3.x"
-      - name: Install Mkdocs
-        run: pip install -r requirements.txt
-      - name: Build Mkdocs
-        run: mkdocs build --config-file docs/mkdocs.yml
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
-        with:
-          path: docs/site
-      - name: Deploy to Github Pages
-        uses: actions/deploy-pages@v4
+  # deploy_mkdocs:
+  #   needs: [ pre-commit ]
+  #   permissions:
+  #     id-token: write
+  #     pages: write
+  #   environment:
+  #     name: github-pages
+  #     url: ${{ steps.deployment.outputs.page_url }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check out
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: "${{ secrets.PAT }}"
+  #     - name: Set up Python
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: "3.x"
+  #     - name: Install Mkdocs
+  #       run: pip install -r requirements.txt
+  #     - name: Build Mkdocs
+  #       run: mkdocs build --config-file docs/mkdocs.yml
+  #     - name: Upload artifact
+  #       uses: actions/upload-pages-artifact@v3
+  #       with:
+  #         path: docs/site
+  #     - name: Deploy to Github Pages
+  #       uses: actions/deploy-pages@v4
 
   # Deploy-Preview:
   #   runs-on: ubuntu-latest
